name = "site-siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "academy.webex.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "add.customlinks.appsflyer.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "admin.shopify.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "adopt.webex.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "ajax.googleapis.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "api.midtrans.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "api22-normal-c-alisg.tiktokv.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "api24-normal-alisg.tiktokv.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "app-stg.gopay.co.id.siren.afrcloud.site", custom_domain = true },
  { pattern = "app.gopay.co.id.siren.afrcloud.site", custom_domain = true },
  { pattern = "app.midtrans.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "appgallery.huawei.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "apphub.webex.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "ava.game.naver.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "bayar.ruangguru.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "bimbel.ruangguru.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "blog.ruangguru.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "blog.webex.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "cache.netflix.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "career.ruangguru.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "cdn.cookielaw.org.siren.afrcloud.site", custom_domain = true },
  { pattern = "cdn.customlinks.appsflyer.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "cdn.discordapp.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "cdn.shopify.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "cdn3.optimizely.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "cf.shopee.co.id.siren.afrcloud.site", custom_domain = true },
  { pattern = "cdnjs.cloudflare.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "collection.linefriends.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "creativeservices.netflix.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "customlinks.appsflyer.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "dashboard.midtrans.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "dev.appsflyer.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "developer.twitter.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "df.game.naver.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "edu.ruangguru.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "facebook.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "fonts.shopifycdn.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "go.appsflyer.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "go.medallia.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "grabacademyportal.grab.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "grabalumni.grab.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "graph.instagram.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "gw.ruangguru.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "help.viu.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "hurricane.lipcon.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "id.linkedin.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "info.udemy.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "investor.fb.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "investor.medallia.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "io.ruangguru.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "kelas.brainacademy.id.siren.afrcloud.site", custom_domain = true },
  { pattern = "linefriendssquare.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "live.iflix.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "marketplace.zoom.us.siren.afrcloud.site", custom_domain = true },
  { pattern = "news.zoom.us.siren.afrcloud.site", custom_domain = true },
  { pattern = "nontontv.vidio.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "npca.netflix.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "partner.zoom.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "partner.zoom.us.siren.afrcloud.site", custom_domain = true },
  { pattern = "quiz.int.vidio.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "quiz.staging.vidio.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "quiz.vidio.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "roboguru.ruangguru.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "s.lazada.co.id.siren.afrcloud.site", custom_domain = true },
  { pattern = "s.shopee.co.id.siren.afrcloud.site", custom_domain = true },
  { pattern = "shopee.co.id.siren.afrcloud.site", custom_domain = true },
  { pattern = "siren.afrcloud.site", custom_domain = true },
  { pattern = "space.byu.id.siren.afrcloud.site", custom_domain = true },
  { pattern = "st1.zoom.us.siren.afrcloud.site", custom_domain = true },
  { pattern = "static.cdn.zooom.us.siren.afrcloud.site", custom_domain = true },
  { pattern = "store.linefriends.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "support.zoom.us.siren.afrcloud.site", custom_domain = true },
  { pattern = "tokopedia.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "vidcast.io.siren.afrcloud.site", custom_domain = true },
  { pattern = "www.altaglobalschool.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "www.altaschool.id.siren.afrcloud.site", custom_domain = true },
  { pattern = "www.brainacademy.id.siren.afrcloud.site", custom_domain = true },
  { pattern = "www.linkedin.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "www.lipcon.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "www.midtrans.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "www.udemy.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "www.zoom.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "www.zoom.us.siren.afrcloud.site", custom_domain = true },
  { pattern = "x.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "zaintest.vuclip.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "zoomcares.zoom.us.siren.afrcloud.site", custom_domain = true },
  { pattern = "zoomgov.com.siren.afrcloud.site", custom_domain = true },
  { pattern = "zoomtopia.com.siren.afrcloud.site", custom_domain = true }
]
[[kv_namespaces]]
binding = "SIREN"
id = "6aeaffa10ea24a0ebabf74ff132cb8dd"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/SirenWeb/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/SirenWeb/refs/heads/main/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/SirenWeb/refs/heads/main/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/SirenWeb/refs/heads/main/web/converter.html"
